/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as QrcodeRouteImport } from './routes/qrcode'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HumanogramaRouteImport } from './routes/humanograma'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const QrcodeRoute = QrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanogramaRoute = HumanogramaRouteImport.update({
  id: '/humanograma',
  path: '/humanograma',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cursos': typeof CursosRoute
  '/documentos': typeof DocumentosRoute
  '/funcionarios': typeof FuncionariosRoute
  '/humanograma': typeof HumanogramaRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/qrcode': typeof QrcodeRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cursos': typeof CursosRoute
  '/documentos': typeof DocumentosRoute
  '/funcionarios': typeof FuncionariosRoute
  '/humanograma': typeof HumanogramaRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/qrcode': typeof QrcodeRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cursos': typeof CursosRoute
  '/documentos': typeof DocumentosRoute
  '/funcionarios': typeof FuncionariosRoute
  '/humanograma': typeof HumanogramaRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/qrcode': typeof QrcodeRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/configuracoes'
    | '/cursos'
    | '/documentos'
    | '/funcionarios'
    | '/humanograma'
    | '/login'
    | '/manager'
    | '/qrcode'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/configuracoes'
    | '/cursos'
    | '/documentos'
    | '/funcionarios'
    | '/humanograma'
    | '/login'
    | '/manager'
    | '/qrcode'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/configuracoes'
    | '/cursos'
    | '/documentos'
    | '/funcionarios'
    | '/humanograma'
    | '/login'
    | '/manager'
    | '/qrcode'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CursosRoute: typeof CursosRoute
  DocumentosRoute: typeof DocumentosRoute
  FuncionariosRoute: typeof FuncionariosRoute
  HumanogramaRoute: typeof HumanogramaRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  QrcodeRoute: typeof QrcodeRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/humanograma': {
      id: '/humanograma'
      path: '/humanograma'
      fullPath: '/humanograma'
      preLoaderRoute: typeof HumanogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CursosRoute: CursosRoute,
  DocumentosRoute: DocumentosRoute,
  FuncionariosRoute: FuncionariosRoute,
  HumanogramaRoute: HumanogramaRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  QrcodeRoute: QrcodeRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
