FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Pré-download do modelo de embedding no build da imagem
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('thenlper/gte-small')"

COPY ./app /app/

EXPOSE 8000