version: '3.8'

services:
  minddesk-ia:
    build: .
    container_name: minddesk_worker
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Live Reload da pasta /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload